name: CI

on:
  pull_request:
    branches: [dev, stg, master]
    types: [opened, reopened, synchronize, edited]
env:
  node_version: "12.x"
  tf_version: "0.12.26" # must match value in terraform-iac/*/app/main.tf

jobs:
  env:
    name: Set Env Vars
    runs-on: ubuntu-latest
    steps:
      - name: Set up DEV Environment Variables
        if: github.base_ref == 'dev'
        run: |
          matrix='{
            "env":[
              {
                "tf_working_dir":"./terraform-iac/dev/app",
                "aws_key_name":"byu_oit_terraform_dev_key",
                "aws_secret_name":"byu_oit_terraform_dev_secret"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up STG Environment Variables
        if: github.base_ref == 'stg'
        run: |
          matrix='{
            "env":[
              {
                "tf_working_dir":"./terraform-iac/stg/app",
                "aws_key_name":"byu_oit_terraform_dev_key",
                "aws_secret_name":"byu_oit_terraform_dev_secret"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

      - name: Set up PRD/CPY Environment Variables
        if: github.base_ref == 'master'
        run: |
          matrix='{
            "env":[
              {
                "tf_working_dir":"./terraform-iac/prd/app",
                "aws_key_name":"byu_oit_terraform_prd_key",
                "aws_secret_name":"byu_oit_terraform_prd_secret"
              },
              {
                "tf_working_dir":"./terraform-iac/cpy/app",
                "aws_key_name":"byu_oit_terraform_prd_key",
                "aws_secret_name":"byu_oit_terraform_prd_secret"
              }
            ]
          }'
          echo matrix=`echo $matrix | jq -c .` >> $GITHUB_ENV

    outputs:
      matrix: ${{ env.matrix }}

  src-test:
    name: Test App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        working-directory: src
        run: npm install

      - name: npm test
        working-directory: src
        run: npm test

  src-audit:
    name: Audit App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: npm audit
        working-directory: src
        run: npm audit --audit-level=critical

  src-lint:
    name: Lint App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: npm install
        working-directory: src
        run: npm install

      - name: npm lint
        working-directory: src
        run: npm run lint

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: |
          docker build src --file src/Dockerfile

  format:
    name: Terraform Format
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform Format
        working-directory: "./"
        run: terraform fmt -check -recursive

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: env
    strategy:
      matrix: ${{ fromJson(needs.env.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[matrix.env.aws_key_name] }}
          aws-secret-access-key: ${{ secrets[matrix.env.aws_secret_name] }}
          aws-region: us-west-2

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform Init
        working-directory: ${{ matrix.env.tf_working_dir }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ matrix.env.tf_working_dir }}
        run: terraform plan -var 'image_tag=ci_test' -input=false -out plan

      - name: Comment Terraform Plan
        uses: byu-oit/github-action-tf-plan-comment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ${{ matrix.env.tf_working_dir }}
          terraform-plan-file: plan

      - name: Analyze Terraform Plan
        uses: byu-oit/github-action-tf-plan-analyzer@v1
        with:
          working-directory: ${{ matrix.env.tf_working_dir }}
          terraform-plan-file: plan
          divvycloud-username: ${{ secrets.DIVVYCLOUD_USERNAME }}
          divvycloud-password: ${{ secrets.DIVVYCLOUD_PASSWORD }}
