name: CI/CD Pipeline

on:
  push:
    branches: [ master, dev, github-actions ]
env:
  tf_version: '0.12.24'

jobs:

  build_and_deploy:
    name: Build and deploy Fargate API to dev
    runs-on: ubuntu-latest
    steps:

    - name: Setup DEV Environment Variables
      if: contains(['refs/heads/dev', 'refs/heads/github-actions'], github.ref)
      run: |
        echo "::set-env name=aws_key::${{ secrets.byu_oit_terraform_dev_key }}"
        echo "::set-env name=aws_secret::${{ secrets.byu_oit_terraform_dev_secret }}"
        echo "::set-env name=ecr_repo_name::hello-world-api-dev"
        echo "::set-env name=tf_working_dir::./terraform-iac/dev/app"
        echo "::set-env name=rfc_client_key::${{ secrets.standard_change_sandbox_client_key }}"
        echo "::set-env name=rfc_client_secret::${{ secrets.standard_change_sandbox_client_secret }}"
        echo "::set-env name=rfc_template_id::Codepipeline-Standard-Change"
        echo "::set-env name=slack_channel::C0AGQEZMF" #slack-bot-testing

    - name: Setup PRD Environment Variables
      if: contains(['refs/heads/master'], github.ref)
      run: |
        echo "::set-env name=aws_key::${{ secrets.byu_oit_terraform_prd_key }}"
        echo "::set-env name=aws_secret::${{ secrets.byu_oit_terraform_prd_secret }}"
        echo "::set-env name=ecr_repo_name::hello-world-api-prd"
        echo "::set-env name=tf_working_dir::./terraform-iac/prd/app"
        echo "::set-env name=rfc_client_key::${{ secrets.standard_change_production_client_key }}"
        echo "::set-env name=rfc_client_secret::${{ secrets.standard_change_production_client_secret }}"
        echo "::set-env name=rfc_template_id::Codepipeline-Standard-Change"
        echo "::set-env name=slack_channel::C014455NV40" #github-actions

    - name: Check out
      uses: actions/checkout@v2

    - name: Disallow Concurrent Runs
      uses: ./.github/actions/disallow-concurrent-runs
      with:
        token: ${{ github.token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.aws_key }}
        aws-secret-access-key: ${{ env.aws_secret }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Get current timestamp
      id: date
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d_%H-%M-%S')"

    - name: Build and Push the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPO: ${{ env.ecr_repo_name }}
        IMAGE_TAG: ${{ steps.date.outputs.timestamp }}
      run: |
        docker build src --file src/Dockerfile --tag $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

    - name: Build Test Lambda
      working-directory: tst/codedeploy-hooks/after-allow-test-traffic
      run: |
        npm install
        cp -R ../../../.postman .
        zip -r lambda.zip * .postman

    - name: 'Terraform Setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.tf_version }}

    - name: 'Terraform Init'
      working-directory: ${{ env.tf_working_dir }}
      run: terraform init

    - name: 'Terraform Plan'
      working-directory: ${{ env.tf_working_dir }}
      run: terraform plan -var 'image_tag=${{ steps.date.outputs.timestamp }}' -out=plan

    - name: Start Standard Change
      uses: ./.github/actions/start-standard-change
      id: start-standard-change
      with:
        client-key: ${{ env.rfc_client_key }}
        client-secret: ${{ env.rfc_client_secret }}
        template-id: ${{ env.rfc_template_id }}

    - name: 'Terraform Apply'
      working-directory: ${{ env.tf_working_dir }}
      run: terraform apply plan

    - name: 'Get CD App Name'
      id: cd-app-name
      working-directory: ${{ env.tf_working_dir }}
      run: terraform output codedeploy_app_name

    - name: 'Get CD Deployment Group Name'
      id: cd-group-name
      working-directory: ${{ env.tf_working_dir }}
      run: terraform output codedeploy_deployment_group_name

    - name: 'Get CD Appspec File'
      id: cd-appspec-file
      working-directory: ${{ env.tf_working_dir }}
      run: terraform output codedeploy_appspec_json_file

    - name: 'CodeDeploy'
      id: deploy
      uses: ./.github/actions/codedeploy
      with:
        application-name: ${{ steps.cd-app-name.outputs.stdout }}
        deployment-group-name: ${{ steps.cd-group-name.outputs.stdout }}
        appspec-file: ${{ steps.cd-appspec-file.outputs.stdout }}

    - name: End Standard Change
      uses: ./.github/actions/end-standard-change
      if: ${{ always() && steps.start-standard-change.outcome == 'success' }} # Run if RFC started, even if the deploy failed
      with:
        client-key: ${{ env.rfc_client_key }}
        client-secret: ${{ env.rfc_client_secret }}
        change-sys-id: ${{ steps.start-standard-change.outputs.change-sys-id }}
        work-start: ${{ steps.start-standard-change.outputs.work-start }}
        success: ${{ steps.deploy.outcome == 'success' }}

    - name: Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        channel: ${{ env.slack_channel }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }} # required
      if: always() # Pick up events even if the job fails or is canceled.
